# Generated by Django 3.2.18 on 2023-03-11 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20230311_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='directions',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
