# Generated by Django 3.2.18 on 2023-03-11 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipeingredient_directions'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='thumb',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
